module.exports = ["marrowbone",
    "fullmetal alchemist",
    "boonie bears: the big top secret",
    "for a few bullets",
    "the disaster artist",
    "room no. 7",
    "detective chinatown 2",
    "explosion",
    "awakening the zodiac",
    "tiger zinda hai",
    "brawl in cell block 99",
    "no life:",
    "once upon a time in the northeast",
    "padai veeran",
    "darkest hour",
    "the gateway",
    "downsizing",
    "paddington",
    "fairy tale of love",
    "sanada 10 braves",
    "mumon: shinobi no kuni",
    "the devotion of suspect x",
    "benji",
    "lies we tell",
    "keep calm and be a superstar",
    "",
    "the night is short, walk on girl",
    "the werewolf game: lovers",
    "kidnapping mr. heineken",
    "message from the king",
    "teiichi no kuni",
    "peace breaker",
    "the secret of s",
    "tad the lost explorer 2: the secret of king midas",
    "acts of violence",
    "cậu em khác người , keys to the heart",
    "wonder",
    "never say die",
    "the chase",
    "phantom thread",
    "proud mary",
    "terrifier",
    "bring on the melody!",
    "the haunted hotel",
    "the bros / brother",
    "along with the gods: the two world",
    "the empty hands",
    "hyouka",
    "all the money in the world",
    "wonder wheel",
    "the commuter",
    "detective k: secret of the living dead",
    "miracles of the namiya general store",
    "jojo’s bizarre adventure: diamond is unbreakable",
    "ghost",
    "namiya zakkaten no kiseki",
    "12 strong",
    "the third murder",
    "steel rain",
    "a better tomorrow",
    "husband killers",
    "gate",
    "goldbuster",
    "the bachelors",
    "the last call",
    "puppy",
    "secret superstar",
    "the star",
    "molly's game",
    "anthology",
    "earth: one amazing day",
    "the post",
    "mystery zone : soul eating hill",
    "hostiles",
    "kinh",
    "batman ninja",
    "jurassic world: fallen kingdom",
    "nên ngắm từ dưới hay bên cạnh, fireworks, should we see it from the side or the bottom?",
    "lost in apocalypse",
    "the last note",
    "the werewolf game: crazy fox",
    "the bold, the corrupt and the beautiful",
    "maya the bee movie",
    "young fabulous",
    "the promise",
    "be with you / now, i am coming to see you",
    "pari",
    "black panther",
    "the hollow child",
    "tubelight",
    "the man who invented christmas",
    "the anthem of the heart / the heart wants to shout",
    "forever my girl",
    "backstabbing for beginners",
    "fifty shades freed",
    "early man",
    "hotel artemis",
    "seven years of night",
    "roman j. israel, esq.",
    "anon",
    "slumber",
    "revenge",
    "unleashed",
    "a quiet place",
    "judwaa 2",
    "mixed doubles",
    "kill me please",
    "the hurricane heist",
    "golden slumber",
    "the week of",
    "death wish",
    "avicii: true stories",
    "the 12th man",
    "sara's notebook",
    "re: born",
    "love simon",
    "mute",
    "growing pains",
    "memoir of a murderer",
    "what a man wants",
    "journey's end",
    "padmaavat",
    "deadpool 2",
    "submergence",
    "forgotten / night of memory",
    "family of winners",
    "gonjiam: haunted asylum",
    "1921",
    "pacific rim: uprising",
    "in the fade",
    "thoroughbreds",
    "terminal",
    "in darkness",
    "honeymoon",
    "americano",
    "ready player one",
    "the",
    "devil's gate",
    "the outsider",
    "paul apostle of christ",
    "actor in law",
    "falling in love",
    "the white helmets",
    "yurigokoro",
    "quackerz",
    "7 days in entebbe",
    "the great buddha",
    "kế hoạch đào",
    "midnight sun",
    "amy",
    "recontroller",
    "game night",
    "to love or not to love",
    "burning",
    "small town crime",
    "the 15:17 to paris",
    "duvvada jagannadham",
    "fences",
    "a fantastic woman",
    "gad elmaleh: american dream",
    "tiger girl",
    "the irregular at magic high school the movie: the girl who calls the stars",
    "plan b",
    "dracula untold",
    "alpha",
    "i remember you",
    "mr. hurt",
    "nanoha: reflection",
    "lino: uma aventura de sete vidas",
    "the last face",
    "24 wochen",
    "police story",
    "ciel rouge",
    "hot young bloods",
    "perfect proposal",
    "tróc yêu ký, monster hunt",
    "i fine thank you love",
    "terminator: genisys",
    "mad max: fury",
    "maze runner: the scorch trials",
    "godzila",
    "two weeks",
    "blood",
    "transformers",
    "transformers 4: age of",
    "last knights",
    "annabelle",
    "the fantastic four",
    "home",
    "the deathday",
    "absolutely anything",
    "pan",
    "heist",
    "maleficent",
    "hollywood adventures",
    "the huntresses",
    "iron man",
    "fall in love like a star",
    "vacation",
    "anohana",
    "impossible",
    "miss granny",
    "chappie",
    "new mutants",
    "the last witch hunter",
    "our times",
    "retribution",
    "iron",
    "gambit",
    "boule et bill",
    "van gogh",
    "the advocate a missing body",
    "avengers 2: age of ultron",
    "pattaya",
    "the danish girl",
    "random aka kristy",
    "le jour des corneilles",
    "i am michael",
    "mindgamers",
    "kung fu panda 3, công phu panda 3, kungfu gấu trúc",
    "zombie fighters",
    "kung fu panda",
    "bóng ma hiện",
    "the boss",
    "deep",
    "midnight special",
    "true legend",
    "ip man 3",
    "skip trace",
    "molly moon",
    "the 5th wave",
    "ride along 2",
    "holidays",
    "joy",
    "from vegas to macau 3",
    "star wars: the force awakens",
    "the monkey king 2",
    "fury",
    "viral",
    "the witch",
    "i am wrath",
    "precious cargo",
    "gods of egypt",
    "zootopia",
    "la prophétie des grenouilles",
    "jack and the cuckoo clock heart",
    "10 cloverfield lane",
    "mike and dave",
    "so close",
    "connasse",
    "summer snow",
    "kuroko no basket: last game",
    "oss 117 rio ne répond plus",
    "il était une forêt",
    "asterix the land of the gods",
    "finding nemo",
    "the dark knight rises",
    "les contes de la nuit",
    "the dark knight",
    "senior",
    "time renegade",
    "batman begins",
    "mune",
    "familyhood",
    "hardcore henry",
    "criminal",
    "close range",
    "broken vow",
    "twilight",
    "palm trees in the snow",
    "my new sassy girl",
    "the four 3: final battle",
    "resident evil 2: apocalypse",
    "marauders",
    "angry birds",
    "before i wake",
    "three",
    "the jungle book",
    "kidnap",
    "before i go to sleep",
    "the nice guys",
    "money monster",
    "san andreas quake",
    "run all night",
    "poltergeist",
    "seondal the man who sells the river",
    "money",
    "the mechanic",
    "detective conan movie 20: the darkest nightmare",
    "under shadow",
    "ratchet and clank",
    "recovery",
    "kickboxer",
    "cold war 2",
    "raid dingue",
    "teenage mutant ninja turtles: out of the shadows",
    "source code",
    "central intelligence",
    "alice through the looking glass",
    "the legend of tarzan",
    "ghost busters 2",
    "indochine",
    "resident evil",
    "sully",
    "lights out",
    "independence day: resurgence",
    "nerve",
    "mr. six",
    "bad moms",
    "project almanac",
    "misconduct",
    "uss indianapolis: men of courage",
    "finding dory",
    "a violent prosecutor",
    "a chinese odyssey 3",
    "power rangers",
    "the whole truth",
    "tales of the night",
    "fast 888",
    "eloise",
    "havenhurst",
    "the karate kid",
    "haunting in japan",
    "a demon within",
    "jason bourne",
    "the perfect weapon",
    "war dogs",
    "crouching tiger hidden dragon",
    "army of one",
    "mechanic: resurrection",
    "the golden compass",
    "buddies in india",
    "ballerina leap!",
    "personal shopper",
    "rupture",
    "colossal",
    "extortion",
    "going in style",
    "open water 3: cage",
    "my cousin rachel",
    "kungfu cyborg",
    "the bfg",
    "the hobbit 3 the battle of the five armies",
    "the evil gene",
    "jack the giant slayer",
    "puppy!",
    "the four",
    "iboy",
    "cargo",
    "split",
    "get out",
    "rings",
    "the ritual",
    "extraordinary mission",
    "life",
    "berlin syndrome",
    "smurfs: the lost village",
    "the villainess",
    "ghost in the shell",
    "the circle",
    "the mummy",
    "doraemon the movie 2017: great adventure in the antarctic kachi",
    "quái xế baby",
    "những kẻ khát tình",
    "chiến lang 2",
    "kim cương bất bại",
    "hàng ma truyện",
    "ngôi nhà ma ám",
    "new year's gift",
    "tokyo ghoul",
    "the snowman",
    "spl iii: paradox",
    "the mountain between us",
    "flatliners",
    "dunkirk dunkirk",
    "battleship island",
    "the adventurers",
    "while you were sleeping",
    "15+ coming of age",
    "teiichi: battle of supreme high",
    "kingsman: the golden circle",
    "midnight runners",
    "blade runner 2049",
    "the admiral roaring currents",
    "the legend of hercules",
    "a chinese ghost story 4",
    "badges of fury",
    "the warriors gate",
    "a wrinkle in time",
    "the legend of the blue sea",
    "the handmaiden",
    "the expendables 2",
    "barely lethal",
    "top secrets",
    "yellow flowers on green grass",
    "life of",
    "waterworld",
    "sharktopus",
    "dragonheart",
    "the king of fighters",
    "mongol: the rise of genghis khan",
    "serenity",
    "the tournament",
    "making family",
    "sky hunter",
    "thor: the dark world",
    "man of steel, super",
    "the transporter refueled",
    "the hobbit: the battle of the five armies",
    "the martian",
    "the man from u.n.c.l.e",
    "300: rise of an empire",
    "ip man: the final fight",
    "the grandmaster",
    "rise of the legend",
    "the monkey king",
    "đổ thành phong vân",
    "the amazing spiderman",
    "the amazing spider man 2: rise of electro",
    "iron man 2",
    "vandal",
    "casse tête chinois",
    "now you see me",
    "the huntsman: winter's war",
    "the twilight saga 3: eclipse",
    "resident evil 4: afterlife",
    "me before you",
    "bastille day",
    "the conjuring 2: the enfield poltergeist",
    "captain america: civil war",
    "resident evil 5: retribution",
    "now you see me 2",
    "ice age: collision course",
    "train to busan",
    "the big friendly giant",
    "ice age 2: the meltdown",
    "ice age: continental drift",
    "rustom",
    "kubo and the two strings",
    "jack reacher: never go back",
    "hotel transylvania 2",
    "pete's dragon",
    "ouija 2",
    "the brothers grimm",
    "hide and seek",
    "i love you too",
    "the raid 2",
    "ben hur",
    "bilal: a new breed of hero",
    "twenty",
    "forrest gump",
    "luck.key",
    "shin godzilla",
    "morgan",
    "bridget jones's baby",
    "eliminators",
    "heartfall arises",
    "your name kimi no na wa",
    "hunt for the wilderpeople",
    "avantyuristy",
    "trolls",
    "keeping up with the joneses",
    "special female force",
    "incarnate",
    "a kind of murder",
    "max steel",
    "the red turtle",
    "the thinning",
    "equals",
    "one day",
    "one piece film: gold",
    "be afraid",
    "family heist",
    "mastermind",
    "the girl with all the gifts",
    "sword master",
    "my annoying brother",
    "arrival",
    "nocturnal animals",
    "don't knock twice",
    "billy lynn's long halftime walk",
    "sadako vs kayako",
    "the rings 3",
    "trận chiến đẫm",
    "passengers",
    "shut in",
    "resident evil 6: the final chapter",
    "monster trucks",
    "sleepless (nc16)",
    "eat local",
    "voice from the stone",
    "before i fall",
    "black butterfly",
    "what happened to monday",
    "quá ít hài hước và quá thừa cảnh hành động không đáng chú",
    "girls 2: girls vs gangsters",
    "the maze runner: the death cure season 3​",
    "den of thieves",
    "hercules",
    "psychokinesis",
    "ajin:",
    "winchester",
    "peter rabbit",
    "marvel's",
    "red sparrow",
    "spiders",
    "lôi báo",
    "the four 3",
    "corbin nash",
    "tremors: a cold day in hell",
    "incoming",
    "downrange",
    "operation red sea",
    "fahrenheit 451",
    "aftermath",
    "quá nhanh quá nguy hiểm",
    "beauty and the beast",
    "xxx 3: the return of xander cage",
    "gringo",
    "the merciless",
    "outrage coda",
    "black water",
    "2036 origin unknown",
    "ghost land",
    "escape plan 2:",
    "john wick: chapter 2",
    "fast & furious season 8: the fate of the furious",
    "king arthur: legend of the sword",
    "spark: a space tail",
    "wind river",
    "inconceivable",
    "wukong",
    "điệp vụ phản gián",
    "nữ thần chiến binh",
    "quảng trường ma",
    "giải cứu công chúa",
    "chơi hay chết",
    "coco",
    "đột kích hồ giấu vàng",
    "hành khách bí ẩn",
    "bản sắc anh hùng",
    "robot đại chiến 5: kỵ sỹ cuối cùng",
    "ngôi làng tiền sử",
    "vùng đất câm lặng",
    "scandal makers remake",
    "ứng dụng ma",
    "cướp biển vùng caribbean 5: người chết không kể chuyện",
    "đại chiến hành tinh khỉ",
    "đội quân cảm xúc",
    "kẻ cắp mặt trăng 3",
    "amityville: quỷ dữ thức tỉnh",
    "the dark tower",
    "xác chết đêm trắng",
    "i can speak",
    "detective conan: crimson love letter",
    "thiên la địa võng",
    "sự nổi dậy hoàn hảo 3",
    "the tunner",
    "cars 3",
    "the invisible guest",
    "the strangers: prey at night",
    "net i die",
    "s.m.a.r.t. chase",
    "guardians of the tomb",
    "keys to the heart",
    "the greatest showman",
    "looking glass",
    "jumanji: welcome to the jungle",
    "justice league",
    "happy family",
    "insidious: chapter 4",
    "ferdinand",
    "daddy's home 2",
    "geostorm",
    "murder on the orient express",
    "star wars: the last jedi",
    "atomic blonde",
    "because i love you",
    "incredibles 2",
    "good bye to good bye",
    "lawless lawyer",
    "rich man, poor man",
    "come and hug me",
    "what's wrong with secretary kim?",
    "marry me now",
    "are you human?",
    "miss hammurabi",
    "about time",
    "interstellar",
    "blair witch",
    "my pet dinosaur",
    "big hero 6",
    "wildling",
    "monster hunt 2",
    "avengers: infinity war",
    "the vanished",
    "rampage",
    "deep blue sea 2",
    "tomb raider",
    "bent",
    "snatch up / money bag",
    "high & low: the movie",
    "bad genius",
    "valerian and the city of a thousand planets",
    "gintama live action",
    "behind the blue door",
    "blade of the immortal",
    "the foreigner",
    "raiders of the lost ark",
    "itazurana kiss part 2: campus hen",
    "good time",
    "monkey king reloaded",
    "realms",
    "ancien and the magic tablet",
    "a christmas prince",
    "sarah silverman: a speck of dust",
    "a loving",
    "almost adults",
    "the legend of feihong",
    "jungle",
    "atm",
    "the incredibles",
    "a walk among the tombstones",
    "sorcery in the big city",
    "barbie: dolphin magic",
    "olaf's frozen adventure",
    "tekken: blood vengeance",
    "dunkirk",
    "hard boiled sweet",
    "mother",
    "everything beautiful is far away",
    "gui quan",
    "when the bough breaks",
    "ingrid goes west",
    "my little pony: the movie",
    "close knit",
    "lucid dream",
    "assassination classroom the movie: 365 days",
    "haunted campus",
    "mudbound",
    "crooked house",
    "american made",
    "bleed for this",
    "the lego ninjago movie",
    "9",
    "mr. donkey",
    "unnatural",
    "the killing of a sacred deer",
    "victoria and abdul",
    "the humanity bureau",
    "hollow in the land",
    "san gatsu no lion",
    "beyond skyline",
    "the pirates of somalia",
    "absurd accid",
    "mayhem",
    "skyline",
    "chasing the dragon",
    "confession of murder",
    "the tag along 2",
    "eternal wave",
    "gerald's game",
    "the scroll of wing chun white crane",
    "el camino christmas",
    "battle of the sexes",
    "breathe",
    "gintama",
    "the chef",
    "border 2",
    "the golden monk",
    "canola",
    "pokémon the movie: i choose you!",
    "bright",
    "memoir",
    "the brink",
    "chân dung tuổi 19, edge of innocence",
    "take me home",
    "detroit",
    "herbalist doctor detective",
    "cat lover",
    "queen of triads",
    "tôi và anh",
    "some like it hot",
    "happy death day",
    "perfect imperfection",
    "found footage 3d",
    "kickboxer: retaliation",
    "the layover",
    "tulip fever",
    "fight",
    "overdrive",
    "suddenly seventeen",
    "god's not dead 2",
    "the bar",
    "the swindlers",
    "loving vincent",
    "sakurada reset: part 1",
    "easy life",
    "brotherhood of blades ii: the infernal battlefield",
    "jigsaw",
    "blue planet ii",
    "jeepers creepers 3",
    "blowtorch",
    "goodbye christopher robin",
    "lady bird",
    "in the fog",
    "a special lady",
    "the preparation",
    "day of the dead: bloodline",
    "girl of the big house",
    "what a wonderful family!",
    "wonderstruck",
    "professor marston and the wonder women",
    "the open house",
    "bridge in clouds",
    "godzilla: monster planet",
    "killing ground",
    "kimi no suizou wo tabetai",
    "i, tonya",
    "lost in the moonlight",
    "the duel",
    "super hero",
    "desierto",
    "20th century women",
    "only the brave",
    "bullet head",
    "the insanity",
    "three billboards outside ebbing, missouri",
    "survival family",
    "who killed cock robin",
    "infini",
    "god's own country",
    "the cloverfield paradox",
    "boy missing / secuestro",
    "giết tôi đi, kill me",
    "monster island",
    "braven",
    "tadeo jones 2: el secreto del rey midas",
    "the liquidator",
    "a taxi driver",
    "the farewell girls",
    "the strange ones",
    "same kind of different as me",
    "dou ji xia",
    "supernatural events",
    "when we first met",
    "bố hư 2 , daddy's home 2",
    "the werewolf game: prison break",
    "on the beach at night alone",
    "wished",
    "didi's dreams",
    "thor: ragnarok",
    "the death of stalin",
    "kungfu hustle",
    "the werewolf game: the villagers side",
    "the crucifixion",
    "10x10",
    "tori girl",
    "blackburn",
    "sanam re",
    "the faces of my gene"
]